### ISSUE TITLE
unable to generate a map

### ISSUE THREAD

**Issue by mikmarin** [psophometric/data-radio-fr#1]
Good evening,
Congratulations for your idea and works.
I'm unable to create any map.
I receive the same type of message error whatever the data I need.
Traceback (most recent call last):
  File "dataradio-map.py", line 114, in <module>
    iframe = folium.element.IFrame(html=html, width=275, height=175)
AttributeError: 'module' object has no attribute 'element'
Tks for your help!

**Comment by psophometric** [comment]
Good evening,
It's an issue since Folium version 0.3.0.
_dataradio-map.py - line 114 :_
` iframe = folium.element.IFrame(html=html, width=275, height=175)`
_It must be edit like that :_
` iframe = folium.IFrame(html=html, width=275, height=175)`

However, today, i have rewriten all the scripts (datamap-up.py & datamap-map.py) to make it works with JSON file format (and folium 0.3.0).
